---
version: 2
controller: {}
workers:
  -
    type: router
    realms:
      -
        name: realm1
        roles:
          -
            name: anonymous
            permissions:
              -
                uri: ""
                match: prefix
                allow:
                  call: true
                  register: true
                  publish: true
                  subscribe: true
                disclose:
                  caller: false
                  publisher: false
                cache: true
    transports:
      -
        type: universal
        endpoint:
          type: tcp
          port: 8080
        rawsocket: {}
        websocket:
            ws:
              type: websocket
        web:
          paths:
            /:
              type: static
              directory: ../dist/client
  -
      type: guest
      executable: python
      arguments:
        - -m
        - server
      options:
        env:
          vars:
            ZEITSONDE_LOGLEVEL: info
            ZEITSONDE_WAMP_ROUTER_URL: ws://localhost:8080/ws
            ZEITSONDE_WAMP_REALM: realm1
            ZEITSONDE_MONGODB_CONNECTION_URI: mongodb://localhost:27017
            ZEITSONDE_MONGODB_DATABASE_NAME: ZeitSonde
        workdir: ..
        watch:
          directories:
            - ../server
          action: restart
